// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbSqYpaQ6YfTg0x2JIUYwcZ4QiadZWmh8',
    appId: '1:720845096985:web:7437616c555a6cfb7c4288',
    messagingSenderId: '720845096985',
    projectId: 'thatnightin-6dd8a',
    authDomain: 'thatnightin-6dd8a.firebaseapp.com',
    storageBucket: 'thatnightin-6dd8a.firebasestorage.app',
    measurementId: 'G-JBHJ0KWQEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiMkV87Cx0vWHwg4j5wGIgyDudwSQ5AXI',
    appId: '1:720845096985:android:b9a3cd57e1df93cc7c4288',
    messagingSenderId: '720845096985',
    projectId: 'thatnightin-6dd8a',
    storageBucket: 'thatnightin-6dd8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB02uVUa5n_fTM-2mLU5QGKQ_yqBs2FfQ',
    appId: '1:720845096985:ios:9c09637a86df381c7c4288',
    messagingSenderId: '720845096985',
    projectId: 'thatnightin-6dd8a',
    storageBucket: 'thatnightin-6dd8a.firebasestorage.app',
    iosBundleId: 'com.abishek.thatnightin',
  );
}
